[Feature] Add training tutorials for CD tasks
PaddleCV-SIG/PaddleRS pull request #33
Opened 2022-03-31 07:19 UTC by Bobholamovic

1. Change the parameter initialization method of FC-EF, FC-Siam-conc, and FC-Siam-diff, such that these networks can be trained to obtained higher detection accuracy.
2. Add training tutorials for all implemented CD methods, except for ChangeStar. The training tutorial of ChangeStar is to be added later, because I have not yet found a suitable dataset. For the other CD methods, the training is performed on the [SZTAKI AirChange Benchmark Set](http://mplab.sztaki.hu/remotesensing/airchange_benchmark.html).

2022-03-31 15:38 UTC, geoyee approved these changes

2022-03-31 15:40 UTC, geoyee commented
不过那个training tutorials需要把所有的网络都写一下吗，还有测试的数据 😃

2022-03-31 15:54 UTC, Bobholamovic commented
> 不过那个training tutorials需要把所有的网络都写一下吗，还有测试的数据 😃

嗯嗯，在另一个分支里已经在写啦

2022-04-02 02:54 UTC, LutaoChu requested changes

2022-04-02 02:54 UTC, LutaoChu commented on tutorials/train/change_detection/bit.py
> +# API说明：https://github.com/PaddlePaddle/paddlers/blob/develop/docs/apis/transforms/transforms.md
链接无效

2022-04-02 02:54 UTC, LutaoChu commented on tutorials/train/change_detection/bit.py
> +# API说明：https://github.com/PaddlePaddle/paddlers/blob/develop/docs/apis/datasets.md
同上。检查一下所有链接吧，删除无效链接

2022-04-02 02:54 UTC, LutaoChu commented on tutorials/train/change_detection/data/AirChange/.gitignore
> +*.zip
此处ignore生效范围仅在AirChange目录下吗

2022-04-02 02:54 UTC, LutaoChu commented on tutorials/train/change_detection/dsamnet.py
> +# API说明：https://github.com/PaddlePaddle/paddlers/blob/develop/docs/apis/transforms/transforms.md
同样需要check链接

2022-04-02 02:54 UTC, LutaoChu commented on tutorials/train/change_detection/unet_siamdiff.py
> +# 变化检测模型FC-Siam-diff训练示例脚本
不是unet-siamdiff吗

2022-04-02 03:49 UTC, Bobholamovic commented on tutorials/train/change_detection/data/AirChange/.gitignore
> +*.zip
是我放错位置了，应该在data目录下生效

2022-04-02 03:50 UTC, Bobholamovic commented on tutorials/train/change_detection/bit.py
> +# API说明：https://github.com/PaddlePaddle/paddlers/blob/develop/docs/apis/transforms/transforms.md
此处是参考paddlex的，不过目前我们好像还没有相关的文档，那这个链接是不是可以先不放？

2022-04-02 03:51 UTC, Bobholamovic commented on tutorials/train/change_detection/unet_siamdiff.py
> +# 变化检测模型FC-Siam-diff训练示例脚本
部分模型的文件名和论文里作者用的名字可能不一样，关于这一点，是否需要规定必须保持一致？

2022-04-02 06:49 UTC, LutaoChu commented on tutorials/train/change_detection/unet_siamdiff.py
> +# 变化检测模型FC-Siam-diff训练示例脚本
不跟论文里的名字一致是什么原因呢？有什么考量吗

2022-04-02 07:00 UTC, Bobholamovic commented on tutorials/train/change_detection/unet_siamdiff.py
> +# 变化检测模型FC-Siam-diff训练示例脚本
其实倒也没有什么特别的考量。因为有部分的实现是有参考原作者的代码的，所以可能只是在文件命名上和原作者的代码一致（原作者的代码和论文中的命名不一致）。我们是不是都改成一致的会更好一些？

2022-04-02 07:20 UTC, LutaoChu commented on tutorials/train/change_detection/unet_siamdiff.py
> +# 变化检测模型FC-Siam-diff训练示例脚本
原来是原作者的typo。那我们帮他改了吧哈哈，改成和论文一致

2022-04-06 07:14 UTC, LutaoChu commented
有冲突

2022-04-06 08:33 UTC, Bobholamovic commented
> 有冲突

冲突已解决。

2022-04-06 10:03 UTC, LutaoChu approved these changes

2022-04-06 10:03 UTC, merged