[Feature] Add training tutorials for segmentation tasks
PaddleCV-SIG/PaddleRS pull request #34
Opened 2022-03-31 07:26 UTC by Bobholamovic

Add training tutorials for all implemented segmentation methods. Since currently, UNet is the only method that handles multispectral (more than three bands) images, the tutorials of the other methods are based on a non-remote-sensing dataset (i.e. the optic_disc_seg dataset). The tutorial of UNet is based on a landcover classification dataset. Test passes locally.

2022-04-02 03:03 UTC, LutaoChu requested changes

2022-04-02 03:03 UTC, LutaoChu commented on tutorials/train/semantic_segmentation/bisenetv2.py
> +DOWNLOAD_DIR = './data/optic/'
optic_disc不是遥感数据，没必要添加到我们的repo里了吧
遥感任务为示例的教程才添加进来吧。波段数可以不限

2022-04-02 03:03 UTC, LutaoChu commented on tutorials/train/semantic_segmentation/bisenetv2.py
> +DOWNLOAD_DIR = './data/optic/'
其他基于optic_disc的教程都改一下吧

2022-04-02 03:04 UTC, LutaoChu commented
除了unet，deeplab也处理多光谱哈

2022-04-02 03:48 UTC, Bobholamovic commented
目前暂时没有找到能比较方便使用的三波段遥感分割数据集（大部分都需要预处理后上传到某个位置，才能直接在demo中下载使用）。现阶段我们是否可以暂时只做UNet和DeeplabV3p的demo呢？

2022-04-02 06:51 UTC, LutaoChu commented
可以的

2022-04-06 07:18 UTC, LutaoChu commented
有冲突

2022-04-06 07:19 UTC, LutaoChu approved these changes

2022-04-06 08:36 UTC, Bobholamovic commented
> 有冲突
冲突已解决。

2022-04-06 10:05 UTC, LutaoChu commented
又出现冲突了。。。辛苦再解决一下

2022-04-06 10:54 UTC, Bobholamovic commented
> 又出现冲突了。。。辛苦再解决一下

已解决。

2022-04-06 11:14 UTC, merged