add 5 flip mode, 3 rotate mode of images
PaddleCV-SIG/PaddleRS pull request #35
Opened 2022-03-31 13:16 UTC by huilin16

add RandomFlipOrRotation in paddlers/transforms/operators.py
add some functions in paddlers/transforms/functions.py

2022-04-02 08:17 UTC, LutaoChu requested changes

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/functions.py
> +                                0, 1, 2, 3, 4, 'h', 'v', 'hv', 'rt2lb', 'rt2lb', 'dia', 'adia'
补充下数字代表的含义

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/functions.py
> +        xxError:
写明具体Error

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/functions.py
> -    im = im[::-1, :, ...]
这块都不用修改，是等价的
```
>>> a=np.array([[1,2,3],[4,5,6]])
>>> b= a[::-1,:,...]
>>> b
array([[4, 5, 6],
       [1, 2, 3]])
>>> a.shape
(2, 3)
>>> a[::-1, :]
array([[4, 5, 6],
       [1, 2, 3]])
```

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/functions.py
> +        img_rt2lb, flipped around the diagonal
为什么叫rt2lb呢

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/functions.py
> +    if len(im.shape) == 3:
按上面的做法可以简化，改用 `...`

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/functions.py
> +    Raises:
所有注释、代码同步上面comment进行修改

2022-04-02 08:17 UTC, LutaoChu commented on paddlers/transforms/operators.py
> +        --we can use this operator in yml config like following ways:
现在我们不支持yml吧

2022-04-02 08:17 UTC, LutaoChu commented on tools/coco_tools/json_InfoShow.py
> +!python /home/aistudio/work/json_infoShow.py \
绝对路径改成相对路径
所有类似文件同步修改

2022-04-02 08:17 UTC, LutaoChu commented on tools/coco_tools/json_Merge.py
> +!python /home/aistudio/work/json_merge.py \
以上coco_tools能补充一个教程示例吗？展示一下各文件间的相互关系和效果，把他们都串起来

2022-04-05 13:12 UTC, huilin16 commented on paddlers/transforms/functions.py
> +                                0, 1, 2, 3, 4, 'h', 'v', 'hv', 'rt2lb', 'rt2lb', 'dia', 'adia'
已补充

2022-04-05 13:13 UTC, huilin16 commented on paddlers/transforms/functions.py
> +        xxError:
已补充

2022-04-05 13:13 UTC, huilin16 commented on paddlers/transforms/functions.py
> -    im = im[::-1, :, ...]
已还原

2022-04-05 13:13 UTC, huilin16 commented on paddlers/transforms/functions.py
> +        img_rt2lb, flipped around the diagonal
已在参数说明中说明

2022-04-05 13:13 UTC, huilin16 commented on paddlers/transforms/functions.py
> +    if len(im.shape) == 3:
已修改

2022-04-05 13:13 UTC, huilin16 commented on paddlers/transforms/functions.py
> +    Raises:
已修改

2022-04-05 13:14 UTC, huilin16 commented on paddlers/transforms/operators.py
> +        --we can use this operator in yml config like following ways:
已修改

2022-04-05 13:14 UTC, huilin16 commented on tools/coco_tools/json_InfoShow.py
> +!python /home/aistudio/work/json_infoShow.py \
已修改

2022-04-05 13:16 UTC, huilin16 commented on tools/coco_tools/json_Merge.py
> +!python /home/aistudio/work/json_merge.py \
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/api_example_cn.md
是像这样用markdown写一个吗

2022-04-06 02:42 UTC, LutaoChu commented on tools/coco_tools/json_Merge.py
> +!python /home/aistudio/work/json_merge.py \
是的，类似于这样写一下怎么用

2022-04-06 02:50 UTC, LutaoChu approved these changes

2022-04-13 06:11 UTC, LutaoChu commented on tools/coco_tools/json_Merge.py
> +!python /home/aistudio/work/json_merge.py \
hi，教程示例什么时候能补充呢

2022-04-13 06:15 UTC, huilin16 commented
之前在忙导师项目，写了一半，这周末提交




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddleCV-SIG/PaddleRS] add 5 flip mode, 3 rotate mode of images (PR #35)





 
@LutaoChu commented on this pull request.
 
 
In tools/coco_tools/json_Merge.py:
 &gt; @@ -0,0 +1,78 @@ +# -*- coding: utf-8 -*-  +# @File             : json_merge.py +# @Author           : zhaoHL +# @Contact          : ***@***.*** +# @Time Create First: 2021/8/1 10:25 +# @Contributor      : zhaoHL +# @Time Modify Last : 2021/8/1 10:25 +''' ***@***.*** Description: +# 合并json文件，可以通过merge_keys控制合并的字段, 默认合并'images', 'annotations'字段 +!python /home/aistudio/work/json_merge.py \  
hi，教程示例什么时候能补充呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-04-13 06:18 UTC, LutaoChu commented
好的，等教程ready后合入

2022-04-15 13:31 UTC, huilin16 commented
> 好的，等教程ready后合入

更新了教程与部分文件的参数信息

2022-04-18 03:59 UTC, LutaoChu commented on docs/data/coco_utils_cn.md
> +![image.png](./assets/1650011491220-image.png)
图片预览为什么显示不出来呢？本地也会这样吗？

2022-04-18 03:59 UTC, LutaoChu commented on docs/data/coco_utils_cn.md
> +# coco_utils说明
为什么叫coco_utils呢？不是在coco_tools目录里吗？

2022-04-18 03:59 UTC, LutaoChu commented on docs/data/coco_utils_cn.md
> +coco_utils是PaddleRS中，用coco类标注文件处理的工具集。
加个跳转链接，说明一下工具集所在位置吧

2022-04-18 05:49 UTC, huilin16 commented on docs/data/coco_utils_cn.md
> +![image.png](./assets/1650011491220-image.png)
本地没问题的，是不是因为我上传的两个版本，第一个版本没有传图片，第二个版本才把图片和assets文件夹加上

2022-04-18 05:50 UTC, huilin16 commented on docs/data/coco_utils_cn.md
> +# coco_utils说明
原本的文件叫coco_utils，搞混了，已经全部改为coco_tools了

2022-04-18 05:50 UTC, huilin16 commented on docs/data/coco_utils_cn.md
> +coco_utils是PaddleRS中，用coco类标注文件处理的工具集。
已添加

2022-04-18 07:03 UTC, LutaoChu commented
LGTM

2022-04-18 07:04 UTC, merged