[Feature] Add training tutorials for classification tasks
PaddleCV-SIG/PaddleRS pull request #37
Opened 2022-04-01 01:59 UTC by Bobholamovic

1. Fix typos and bugs in `paddlers/datasets/cd_dataset.py` and `paddlers/utils/utils.py`.
2. Update readme file for training tutorials.
3. Add training tutorials for classification tasks. The training of the classification models is based on [the UC Merced land use dataset](http://weegee.vision.ucmerced.edu/datasets/landuse.html).

2022-04-01 02:47 UTC, geoyee commented
- 晖哥是不是分支最好都从develop来，develop只同步上游。看这个cls的分支里面还有前面cd和seg的修改，那是不是merge了这个pr就算把前面的都merge了。
- ppclas的模型全是那种封的很紧的，什么_large，什么1x什么的，这个导入task晖哥有啥看法能方便点不。

2022-04-01 02:56 UTC, Bobholamovic commented
> * 晖哥是不是分支最好都从develop来，develop只同步上游。看这个cls的分支里面还有前面cd和seg的修改，那是不是merge了这个pr就算把前面的都merge了。
> * ppclas的模型全是那种封的很紧的，什么_large，什么1x什么的，这个导入task晖哥有啥看法能方便点不。

+ 我的锅。没注意前面在develop还commit了一次，结果最近的分支全带上了…… 下次注意！
+ 我之前不太熟悉，你刚才这么一说我去看了下，好像PPClas的模型还真都是些本来就在名字里指定了spec的，我原先还以为是为了避免在全局字典里和PPSeg的模型撞key。这方面的话，州哥觉得是不是教程里也遵循PPClas的名字、把规格列出来比较好？关于导出的，因为目前我们所有任务的训练器在一个命名空间里，确实有容易撞key的危险（比如我写变化检测的UNet的时候发现这个 名字已经被占了），后面我们可能修改一下设计或者制定一份命名规则？

2022-04-02 03:56 UTC, LutaoChu requested changes

2022-04-02 03:56 UTC, LutaoChu commented on tutorials/train/README.md
> -* 若需使用多张GPU卡进行训练，例如使用2张卡时执行：
为什么删掉多卡部分呢

2022-04-02 03:56 UTC, LutaoChu commented on tutorials/train/classification/hrnet.py
> +# ucmerced_dataset = 'http://weegee.vision.ucmerced.edu/datasets/UCMerced_LandUse.zip'
取消注释？

2022-04-02 03:56 UTC, LutaoChu commented on tutorials/train/classification/hrnet.py
> +# API说明：https://github.com/PaddlePaddle/paddlers/blob/develop/docs/apis/transforms/transforms.md
移除所有无效链接

2022-04-02 03:56 UTC, LutaoChu commented on tutorials/train/classification/hrnet.py
> +# ucmerced_dataset = 'http://weegee.vision.ucmerced.edu/datasets/UCMerced_LandUse.zip'
同步修改另外几个模型

2022-04-02 03:59 UTC, Bobholamovic commented on tutorials/train/README.md
> -* 若需使用多张GPU卡进行训练，例如使用2张卡时执行：
因为注意到这个README前面有“均使用单块GPU训练”的描述，和后面的多卡部分似乎冲突了。那我们是否保留后者而改变前面的说法？

2022-04-02 07:01 UTC, LutaoChu commented on tutorials/train/README.md
> -* 若需使用多张GPU卡进行训练，例如使用2张卡时执行：
好的

2022-04-02 07:01 UTC, LutaoChu commented on tutorials/train/README.md
> +* 在安装PaddleRS后，使用如下命令开始训练。代码会自动下载训练数据, 并均使用单张GPU卡进行训练。以DeepLab V3+图像分割模型为例：
这里不强调单卡，只强调用GPU训练即可

2022-04-02 07:01 UTC, LutaoChu commented on tutorials/train/README.md
这里注明是单卡训练

2022-04-06 07:16 UTC, LutaoChu commented
有冲突

2022-04-06 07:17 UTC, LutaoChu approved these changes

2022-04-06 08:24 UTC, Bobholamovic commented
> 有冲突

冲突已解决。

2022-04-06 10:02 UTC, merged