[Fix] fix pca used
PaddleCV-SIG/PaddleRS pull request #78
Opened 2022-05-01 03:28 UTC by geoyee

晖哥根据昨天我们关于pca的讨论，今天我尝试修改了一下，首先是`tools`中有个pca.py，可以对一张hsi图像进行pca降维，在保存结果的同时保存pca的参数，如下

![R%HWFQMO`}40)5@TS}4)9 B](https://user-images.githubusercontent.com/71769312/166130702-3c02e729-fb60-4e0e-adb9-206e7218516d.png)

![WL{)LUI@F4P3YS`3(RX`CHS](https://user-images.githubusercontent.com/71769312/166130704-7afd155b-ddb1-4fb7-93ff-a2ee816bb230.png)

但是transform里面还是保留了，作用是比如推理的时候，可以加载这个pca参数进行推理，加载和保存都是这个`*.joblib`的文件，一个test.py如下：

``` python
import paddlers as pdrs
from paddlers import transforms as T
import cv2

transforms = T.Compose([
    T.DimReducing("pcatest/output/UINT16_HSI_pca.joblib")
])

dataset = pdrs.datasets.ClasDataset(
    data_dir='pcatest',  # 里面只有一张图
    file_list='pcatest/list.txt',  # 里面只有这张图的名字和一个标签
    transforms=transforms
)

for data in dataset:
    img = data["image"]
    print(img.shape)
    cv2.namedWindow('img', cv2.WINDOW_NORMAL)
    cv2.imshow("img", cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    cv2.waitKey(0)
    cv2.destroyAllWindows()
```

测试这样的pca

![75@AJ69737ILU23{PH6{Q27](https://user-images.githubusercontent.com/71769312/166130748-26eeb328-3ba6-4fb1-a8a2-0a1ad7a2d383.png)

![SP(6K_85Q1OU$94@1UH3NA4](https://user-images.githubusercontent.com/71769312/166130750-e046af66-b034-4c24-837f-2edd18e70f61.png)

晖哥看看这样可以吗。中间我比较困惑是我应不应该转uint8两次，首先是现在`ImgDecoder`是默认用了`to_uint8`，我想如果训练pca的时候没有这个就会导致不同我就用了，然后就是得到的结果我看有是float64有正有负，如果不`to_uint8`一下会不会影响后面的`Normalize`，所以我也用了。

还有关于`save_tiff`这里有一些重复，和geojson分支，我想等后面这两个合并了我再删一下，顺便再更新文档。

2022-05-01 05:03 UTC, Bobholamovic requested changes
州哥辛苦啦！我对这一块设计上总体没啥疑问，但关于转uint8的问题，可能还需要修改一下，我写在review里了~

2022-05-01 05:03 UTC, Bobholamovic commented on paddlers/transforms/operators.py
> +from joblib import load
joblib为第三方库，按照咱们的代码风格应该放在第二组import中~

2022-05-01 05:03 UTC, Bobholamovic commented on paddlers/transforms/operators.py
> +        result = to_uint8(result)
关于是否该转uint8的问题我请教了一下专业人士，得到的结论是：在对于高光谱影像，在decode后和PCA后都不该转为uint8，而应该保留处理后原始的取值范围。对于高光谱影像，用户在构建transforms时应该对应地使用配套的归一化方式，比如最大-最小映射归一化、zscore归一化等。

2022-05-01 05:55 UTC, geoyee commented
> 州哥辛苦啦！我对这一块设计上总体没啥疑问，但关于转uint8的问题，可能还需要修改一下，我写在review里了~

收到晖哥，先把51过了回来改

2022-05-04 03:03 UTC, geoyee commented
晖哥 @Bobholamovic ，看看现在呢，这是测试数据和代码 [https://next.a-boat.cn:2021/s/ZcnCZCaja9j2ZQn](https://next.a-boat.cn:2021/s/ZcnCZCaja9j2ZQn)

2022-05-04 04:08 UTC, Bobholamovic approved these changes
目前的处理LGTM。不过我觉得后续咱们可能需要把`compose`中hard-code的`decode`给解耦出来，说实话我觉得这两个绑定在一起本身就有些奇怪……

2022-05-04 04:09 UTC, Bobholamovic commented
> 目前的处理LGTM。不过我觉得后续咱们可能需要把`compose`中hard-code的`decode`给解耦出来，说实话我觉得这两个绑定在一起本身就有些奇怪……

这一点还需要再讨论一下，如果确实要重构的话可以另开一个PR做。

2022-05-04 05:25 UTC, geoyee commented
> 

了解~

2022-05-19 09:58 UTC, LutaoChu commented
有冲突

2022-05-19 11:40 UTC, geoyee commented
> 有冲突

已解决~

2022-06-23 02:10 UTC, merged